mode: dev # dev or prod
seed: 430 # seed is ignored in prod mode

num_epochs: 200

image_path: summer2winter_yosemite
batch_size: 32
image_size: 128

channel_size: 64
num_residuals: 6 # number of residual blocks in cycle generator

# cycle loss configs
cycle_loss_multiplier: 10

# optimizers configs
learning_rate: 0.0002
beta1: 0.5
beta2: 0.999

# training configs (-1 => off)
print_freq: 5
eval_freq: 10
save_freq: -1
